//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace ranker.lib.YahooAPI.WebSearchResponse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:yahoo:srch", IsNullable=false)]
    public class ResultSet {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public ResultType[] Result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsAvailable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsReturned;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string firstResultPosition;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srch")]
    public class ResultType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Summary;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string ClickUrl;
        
        /// <remarks/>
        public string ModificationDate;
        
        /// <remarks/>
        public string MimeType;
        
        /// <remarks/>
        public CacheType Cache;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srch")]
    public class CacheType {
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string Size;
    }
}

namespace ranker.lib.YahooAPI.InlinkDataResponse {
    using System.Xml.Serialization;
    
    
    //This source code was auto-generated by MonoXSD

    /// <remarks/>
    [System.Xml.Serialization.XmlType(Namespace="urn:yahoo:srch"),
    System.Xml.Serialization.XmlRoot(Namespace="urn:yahoo:srch")]
    public class ResultSet {

        /// <remarks/>
        [System.Xml.Serialization.XmlElement()]
        public ResultType[] Result;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute(DataType="integer")]
        public string totalResultsAvailable;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute(DataType="integer")]
        public string totalResultsReturned;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute(DataType="integer")]
        public string firstResultPosition;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlType(Namespace="urn:yahoo:srch")]
    public class ResultType {

        /// <remarks/>
        public string Title;

        /// <remarks/>
        public string Url;

        /// <remarks/>
        public string ClickUrl;
    }    
    
}
